### ISSUE TITLE
Some usage questions

### ISSUE THREAD

**Issue by genox** [RSC-Labs/medusa-affiliate-discount#6]
Hi,

I am looking to use this plugin and I have a couple of questions before I jump into it:

1. The discount code can be sent to the regular discount code endpoint, correct?
2. How does this reflect on the cart if a valid code has been applied? Is there a flag to make a distinction between regular discount codes and affiliate discount codes?

Thanks in advance for the info :)

**Comment by radoslaw-sz** [comment]
hi @genox - it's been a while when I was implementing it but I will try to answer :)

> The discount code can be sent to the regular discount code endpoint, correct?

Discount code used in a plugin is just an discount code which is used in Medusa - in this manner I changed nothing. The plugin itself does not create discount code, it just reads it.

> How does this reflect on the cart if a valid code has been applied? Is there a flag to make a distinction between regular discount codes and affiliate discount codes?

This is the very same discount code :) This plugin just reuse existing discount codes by putting some additional information in database.

I am not sure if it will help, but details how the plugin works can be found here: https://github.com/RSC-Labs/medusa-affiliate-discount?tab=readme-ov-file#how-it-works

Let me know if this explanation is enough and thanks for the interest!

**Comment by genox** [comment]
Hi @radoslaw-sz and thanks for your answer.

Let me rephrase the second question:

Is it possible to make a distinction during checkout whether an affiliate discount or a regular discount has been applied? I wonder if I can format/use different text for this kind of discounts or whether there is no flags or meta information available to make an assumption about wether this is an affiliate discount code or a standard discount code. Just for formatting purposes, as this would make it possible to highlight the affiliate program specifically without resorting to some prefix/suffix on the codes used.

I read the "how it works" paragraph, but I just want to confirm my take away as it was not entirely clear to me (wether that is a "lost in translation thing" or "me being slow" - I dont know ;) ).

- Discount code is regular medusa discount code
- Once applied to a cart, the customer sees the percentage subtracted as is the case with standard discount codes
- The "affiliate account" essentially has the discounted amount added to his total "earnings"

This is important to me (I need to explain this to the shop owner) as it has the following business implications:

- A 10% affiliate discount coupon means: 10% less earnings and 10% more fix cost for products on an order-> margin is not only reduced by the discount for the shop customer but the fix cost increase due to the transfer of this discount to be paid out to the affiliate.


Sorry for the complicated question and stuff ;)

**Comment by radoslaw-sz** [comment]
> Is it possible to make a distinction during checkout whether an affiliate discount or a regular discount has been applied? I wonder if I can format/use different text for this kind of discounts or whether there is no flags or meta information available to make an assumption about wether this is an affiliate discount code or a standard discount code. Just for formatting purposes, as this would make it possible to highlight the affiliate program specifically without resorting to some prefix/suffix on the codes used.

Ok, now I get your point :) The short answer - it is not possible "out of the box", I mean plugin does not provide such functionality. But you can achieve by creating new API which will call affiliateDiscount service, explictly a function: "getAffiliateDiscountsByDiscountId". If it will return "empty", then it is normal discount code, if returns something, then it is affiliate discount (discount code assigned). Then on your store frontend you can show something. The only (minor) security risk is that it returns also information about customerId and earnings, but I am not sure how people could exploit it.

> This is important to me (I need to explain this to the shop owner) as it has the following business implications:
A 10% affiliate discount coupon means: 10% less earnings and 10% more fix cost for products on an order-> margin is not only reduced by the discount for the shop customer but the fix cost increase due to the transfer of this discount to be paid out to the affiliate.

Not quite, I mean you have two separated things. The first one is a discount code which can have its own configuration (it can be percentage, fixed discount etc.). The second one is "commission" which is the part of affiliation. Here only the percentage is supported now. So in theory you can have something like:
- discount code which gives fixed discount 5$
- commission 0.15

So if product normally cost 200$, then for the client it costs 195$ and 30$ (15% of 200$) goes as earnings.

**Comment by genox** [comment]
Thanks so much for elaborating. I tested the plugin on my staging instance and I think I understand how things work now ;)

I gave it a spin on my staging instance and was able to configure things as expected. However, the running total of affiliate bonus has not been increased after making a test order with the discount, capturing the payment and going thru the order states until shipped. I checked my logs but wasn't able to find anything suspicious.

Usage count and earnings remain at 0 after several orders.

I am using the latest versions of both medusajs and your plugin. Payment provider is stripe.

**Comment by radoslaw-sz** [comment]
hi @genox  - did you mark the Order as COMPLETED? Please take a look at the note here:
https://github.com/RSC-Labs/medusa-affiliate-discount/blob/main/README.md#details

If you do not have custom implementation which marks orders as COMPLETED, then you can try to configure this plugin to use PAYMENT_CAPTURED, see this:
https://github.com/RSC-Labs/medusa-affiliate-discount/blob/main/README.md#configuration

Please also see the "warning" mentioned there.

**Comment by genox** [comment]
Thank you. It works now. Thank you for opensourcing this plugin!
